export const FETCH_HOME_DATA = `FETCH_HOME_DATA`;
export const FETCH_HOME_SUCCESS = `FETCH_HOME_SUCCESS`;
export const FETCH_HOME_FAIL = `FETCH_HOME_FAIL`;

export const FETCH_PROJECTS_DATA = `FETCH_PROJECTS_DATA`;
export const FETCH_PROJECTS_SUCCESS = `FETCH_PROJECTS_SUCCESS`;
export const FETCH_PROJECTS_FAIL = `FETCH_PROJECTS_FAIL`;

export const FETCH_PROJECT_DATA = `FETCH_PROJECT_DATA`;
export const FETCH_PROJECT_SUCCESS = `FETCH_PROJECT_SUCCESS`;
export const FETCH_PROJECT_FAIL = `FETCH_PROJECT_FAIL`;

export const FETCH_CONNECT_DATA = `FETCH_CONNECT_DATA`;
export const FETCH_CONNECT_SUCCESS = `FETCH_CONNECT_SUCCESS`;
export const FETCH_CONNECT_FAIL = `FETCH_CONNECT_FAIL`;

export const REGISTER_USER = `REGISTER_USER`;
export const REGISTER_USER_SUCCESS = `REGISTER_USER_SUCCESS`;
export const REGISTER_USER_FAIL = `REGISTER_USER_FAIL`;

export const FETCH_VIDEO_DATA = `FETCH_VIDEO_DATA`;
export const FETCH_VIDEO_SUCCESS = `FETCH_VIDEO_SUCCESS`;
export const FETCH_VIDEO_FAIL = `FETCH_VIDEO_FAIL`;

export const FETCH_PAPER_DATA = `FETCH_PAPER_DATA`;
export const FETCH_PAPER_SUCCESS = `FETCH_PAPER_SUCCESS`;
export const FETCH_PAPER_FAIL = `FETCH_PAPER_FAIL`;

export const FETCH_PROFILE_DATA = `FETCH_PROFILE_DATA`;
export const FETCH_PROFILE_SUCCESS = `FETCH_PROFILE_SUCCESS`;
export const FETCH_PROFILE_FAIL = `FETCH_PROFILE_FAIL`;

export const FETCH_USER_DATA = `FETCH_USER_DATA`;
export const FETCH_USER_SUCCESS = `FETCH_USER_SUCCESS`;
export const FETCH_USER_FAIL = `FETCH_USER_FAIL`;
